name: release

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [12.x]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: npm build
      run: npm run build
      env:
        MNENOMIC: ${{secrets.MNENOMIC}}
        INFURA_API_KEY: ${{secrets.INFURA_API_KEY}}

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: networks-$GITHUB_REF-$GITHUB_SHA
        path: bondappetit.tokenlist.json

    - name: Publish
      run: |
        git config --global user.name 'Bondappetit CI'
        git config --global user.email 'hello@bondappetit.io'
        cd $GITHUB_WORKSPACE
        git remote add origin https://${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git
        git add .
        git commit -m "new build ${{ github.event.release.tag_name }}"
        git push origin master
